# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - install
  - test
  - coverage
  - docs
  - publish

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

cache:
  paths:
    - .cache/pip
    - hypervenv/

before_script:
  - apt-get update && apt-get install --assume-yes python3 python3-pip python3-venv python3-matplotlib
  - python3 --version
  - python3 -m venv hypervenv --without-pip --system-site-packages
  - source hypervenv/bin/activate

install-latest:
  stage: install
  image: python:latest
  when: manual
  script:
    - python setup.py check
    - pip install .

install-slim:
  stage: install
  image: python:slim
  when: manual
  script:
    - python setup.py check
    - pip install .

install-bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: install
  when: manual
  script:
    - pip3 install .

install-bookworm:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bookworm-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: install
  when: manual
  script:
    - python3 -m venv hypervenv --without-pip --system-site-packages
    - source hypervenv/bin/activate
    - python3 -m pip install .

test-pip:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: test
  when: manual
  script:
    - pip3 install hypertiling

unit-test-plain:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
    stage: test
    when: manual
    script:
        - apt-get install -y python3-networkx
        - pip3 install .
        
        - echo "Testing without fancy packages, such as numba..."
        - python3 -m tests.test_core
        - python3 -m tests.test_dynamic
        - python3 -m tests.test_neighbours
        - python3 -m tests.test_compare_neighbours
        
        - echo "Testing reflection kernel without numba"
        - python3 -m tests.test_reflectionkernel
        - python3 -m tests.test_grg
        - python3 -m tests.test_grgs


unit-test-fancy:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
    stage: test
    when: manual
    script:
        - apt-get install -y python3-sortedcontainers python3-numba python3-networkx
        - pip3 install .
        
        - echo "Testing with numba and sortedcontainers..."
        - python3 -m tests.test_core
        - python3 -m tests.test_dynamic
        - python3 -m tests.test_neighbours
        - python3 -m tests.test_compare_neighbours
        
        - echo "Testing reflection kernel without numba"
        - python3 -m tests.test_reflectionkernel
        - python3 -m tests.test_grg
        - python3 -m tests.test_grgs


sphinx-doc:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: docs
  artifacts:
    paths:
      - doc/*
  script:
    - apt-get update
    - apt-get install -y python3-numpy python3-colorama python3-h5py doxygen python3-breathe git python3-sphinx-rtd-theme pandoc python3-networkx
    - pip install --upgrade pip
    - pip install pypandoc sphinx-mdinclude
    - pip install sphinx --upgrade
    - pip install sphinx-rtd-theme --upgrade
    - pip install nbsphinx --upgrade
    - cd doc
    - mkdir examples
    - cd examples
    - cp ../../examples/*.ipynb .
    - cd ..
    - ls
    - sphinx-build . html

send-snapshot:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: install
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+/
  script:
    - apt-get install -y git
    - ./assets/zenodo.sh
    - git archive --format zip --output ${CI_COMMIT_TAG#v}.zip ${CI_COMMIT_TAG}
    - g2z-send -p -m .zenodo.json ${CI_COMMIT_TAG#v}.zip





coverage:
  stage: coverage
  image: python:latest
  before_script:
    - python -m venv env
    - source env/bin/activate
    - pip install pytest
    - pip install pytest-cov
  script:
    - pip install .[test]
    - pytest --doctest-modules --cov --cov-config=pyproject.toml --cov-branch --cov-report term --cov-report html:build/coverage --junitxml=report.xml
    - coverage report
    - coverage xml
    - pip install anybadge==1.9.0
    - mkdir -p build/badges

    # MAINTAINABILITY BADGE
    - pip install radon==5.1.0
    - python -m radon cc --total-average -nB -s hypertiling
    
    # generate a badge for the maintainability index with the total average of cyclomatic complexity as value
    - python -m anybadge --label=Maintainability --value="$(python -m radon cc --total-average -nc hypertiling | tail -n 1 | cut -d' ' -f 3) ($(python -m radon cc --total-average -nc hypertiling | tail -n 1 | cut -d' ' -f 4 | cut -c 2-4))" -f build/badges/maintainability -o
    
    # DOCUMENTATION BADGE
    # generate a badge for the documentation with the current version as label
    # - color: #1082C2 corresponds to the default "informational" color set by https://shields.io
    # this is some magic to retrieve the package version:
    # - python -m anybadge --label=Documentation --value="v$(python -m hypertiling --version)" --color "#1082C2" -f build/badges/documentation -o
    # here it is set manually:
    # - python -m anybadge --label=Documentation --value="v1.3" --color "#1082C2" -f build/badges/documentation -o
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

    paths:
      - build/coverage
      - build/badges
      #- env/   # too large ...



pages:
  stage: publish
  image: python:latest
  needs:
    - coverage
  before_script:
    - ''
  #only:
  #  - main
  #  - staging
  script:
    - mkdir -p public
    - python -m venv env
    - source env/bin/activate
    - pip install .[doc]
    #- DOCS_TARGET=public make docs
    - mv build/badges public/.
    - mv build/coverage public/.
  artifacts:
    paths:
      - public
