import os
import numpy as np
from IPython.display import SVG, display
from abc import ABC, abstractmethod

class SVGElement(ABC):
    """
    Abstract base class for SVG elements with common styling.

    Parameters
    ----------
    fill : str, optional
        Fill color (default: "none")
    edgecolor : str, optional
        Edge color (default: "black")
    lw : float, optional
        Line width (default: 1.0)
    digits : int, optional
        Number of decimal digits for floating point numbers
        in the SVG string (default: 5)
    **svg_attrs : dict, optional
        Additional SVG attributes

    Notes
    -----
    SVG elements generated by this class will have the following common
    attributes: fill, stroke (edgecolor), and stroke-width (lw).
    """
    
    def __init__(
        self,
        fill: str = "none",
        edgecolor: str = "black",
        lw: float = 1.0,
        digits: int = 5,
        **svg_attrs,
    ):
        self.fill = fill
        self.edgecolor = edgecolor
        self.lw = lw
        self.digits = digits
        self.svg_attrs = svg_attrs
    
    @abstractmethod
    def to_svg(self) -> str:
        """Generate the SVG string representation."""
        pass
    
    def __repr__(self):
        """Developer-friendly representation."""
        attrs = ", ".join(f"{k}={v!r}" for k, v in self._get_repr_attrs().items())
        return f"{self.__class__.__name__}({attrs})"
    
    def __str__(self):
        """User-friendly representation."""
        return self._get_str_repr()
    
    def _get_repr_attrs(self) -> dict:
        """
        Override in subclasses to specify which attributes to show in repr.
        Default shows common styling attributes.
        """
        return {
            "fill": self.fill,
            "edgecolor": self.edgecolor,
            "lw": self.lw,
        }
    
    def _get_str_repr(self) -> str:
        """
        Override in subclasses for custom user-friendly string.
        Default returns class name.
        """
        return f"{self.__class__.__name__}"
    
    # Common setters
    def set_fill(self, color: str):
        """Change fill color."""
        self.fill = color
        return self
    
    def set_edgecolor(self, color: str):
        """Change edge color."""
        self.edgecolor = color
        return self
    
    def set_linewidth(self, lw: float):
        """Change line width."""
        self.lw = lw
        return self
    
    def set_attr(self, **attrs):
        """Set additional SVG attributes."""
        self.svg_attrs.update(attrs)
        return self
    
    def _build_base_attrs(self, extra: dict = None) -> dict:
        """Build common attributes dict."""
        attrs = {
            "fill": self.fill,
            "stroke": self.edgecolor,
            "stroke-width": self.lw,
        }
        if extra:
            attrs.update(extra)
        return attrs
    




class SVGCanvas:
    """
    Canvas holding SVG elements that can be modified before rendering.
    
    Parameters
    ----------
    center : tuple[float, float], optional
        Center coordinates (cx, cy) in disk space.
    radius : float, optional
        Disk radius in disk space.
    padding : float, optional
        Padding around the viewBox.
    width : int, optional
        SVG width in pixels.
    height : int, optional
        SVG height in pixels.
    """
    
    def __init__(
        self,
        center: tuple[float, float] = (0, 0),
        radius: float = 100.0,  # corresponds to scale factor in to_px (improve me!)
        padding: float = 5,
        width: int = 600,
        height: int = 600,
    ):
        self.elements: list[SVGElement] = []
        
        # SVG parameters
        self.center = center
        self.radius = radius
        self.padding = padding
        self.width = width
        self.height = height
    
    def add(self, *elements: SVGElement):
        """Add one or more elements."""
        self.elements.extend(elements)
        return self
    
    def remove(self, element: SVGElement):
        """Remove an element."""
        self.elements.remove(element)
        return self
    
    def clear(self):
        """Remove all elements."""
        self.elements.clear()
        return self
    
    def _build_header(self) -> str:
        """Build SVG opening tag with viewBox."""
        cx, cy = self.center
        r = self.radius
        vb_min_x = cx - r - self.padding
        vb_min_y = cy - r - self.padding
        vb_width = 2 * r + 2 * self.padding
        vb_height = 2 * r + 2 * self.padding
        
        return (
            f"<svg xmlns='http://www.w3.org/2000/svg' "
            f"width='{self.width}' height='{self.height}' "
            f"viewBox='{vb_min_x} {vb_min_y} {vb_width} {vb_height}'>\r"
        )
    
    def _build_footer(self) -> str:
        """Build SVG closing tag."""
        return "</svg>\r"
    
    def render(self) -> str:
        """Render complete SVG document."""
        parts = [self._build_header()]
        
        # Add all elements in order
        for elem in self.elements:
            parts.append(elem.to_svg())
            parts.append("\r")
        
        parts.append(self._build_footer())
        return "".join(parts)
    
    def save(self, filename: str):
        """Save SVG to file."""
        with open(filename, 'w') as f:
            f.write(self.render())
        return self
    
    # Collection interface
    def __len__(self): 
        return len(self.elements)
    
    def __getitem__(self, idx): 
        return self.elements[idx]
    
    def __iter__(self): 
        return iter(self.elements)
    
    def __repr__(self):
        return f"SVGCanvas({len(self.elements)} elements)"

def build_svg_attrs(base_attrs: dict, **svg_attrs) -> str:
    """
    Merge base attributes with additional SVG attributes.
    Converts underscores to hyphens (stroke_width -> stroke-width).
    svg_attrs override base_attrs.
    
    Example:
        build_svg_attrs({"fill": "red", "stroke": "black"}, opacity=0.5)
        # Returns: "fill='red' stroke='black' opacity='0.5'"
    """
    base_attrs.update({k.replace('_', '-'): v for k, v in svg_attrs.items()})
    return " ".join(f"{k}='{v}'" for k, v in base_attrs.items())


def to_px(z, factor=100):
    """
    Transforms complex number to px coordinates

    Arguments:
    ----------
    z : np.complex
        coordinate in the complex plane
    factor : int
        some large scaling factor to conform to px scale
    """
    x = np.real(z)
    x *= factor
    y = np.imag(z)
    y *= factor
    return x, y



def draw_svg(content: str):
    """
    Use IPython display API for displaying SVG
    """
    display(SVG(data=content))


def write_svg(fname: str, content: str):
    """
    Write svgString to file
    
    Parameters
    ----------
    fname : str
        filename to write the svg string to
    content : str
        svg string to write to file
    """
    os.remove(fname) if os.path.exists(fname) else None
    svgfile = open(fname, 'w')
    svgfile.write(content)
    svgfile.close()





class SVGGroup(SVGElement):
    """
    A group element that can contain other SVG elements with transformations.
    
    Useful for placing, rotating, and scaling arbitrary SVG content at specific
    locations in the Poincaré disk with proper hyperbolic metric scaling.
    
    Parameters
    ----------
    svg_content : str
        Raw SVG markup to be wrapped in a <g> tag.
    center : complex, optional
        Position in the Poincaré disk where to place the content. Default is origin.
    scale : float, optional
        Scaling factor. For hyperbolic metric scaling, use (1 - |z|²) where z is center.
    rotation : float, optional
        Rotation angle in radians (counterclockwise).
    digits : int, optional
        Decimal precision for SVG coordinates.
    **svg_attrs
        Additional SVG attributes for the group.
    
    Examples
    --------
    >>> # Place a custom SVG at a specific location
    >>> from hypertiling.graphics.svg import SVGCanvas, SVGGroup
    >>> import numpy as np
    >>> canvas = SVGCanvas()
    >>> svg_content = '<circle cx="0" cy="0" r="10" fill="red"/>'
    >>> group = SVGGroup(svg_content, center=0.5+0.3j, scale=0.5, rotation=np.pi/4)
    >>> canvas.add(group)
    SVGCanvas(1 elements)
    """
    
    def __init__(
        self,
        svg_content: str,
        center: complex = 0+0j,
        scale: float = 1.0,
        rotation: float = 0.0,
        digits: int = 5,
        **svg_attrs,
    ):
        super().__init__("none", "none", 0, digits, **svg_attrs)
        self.svg_content = svg_content
        self.center = center
        self.scale = scale
        self.rotation = rotation
    
    def _get_repr_attrs(self) -> dict:
        return {
            "center": self.center,
            "scale": self.scale,
            "rotation": f"{np.rad2deg(self.rotation):.1f}°",
        }
    
    def _get_str_repr(self) -> str:
        return f"SvgGroup(center={self.center:.2f}, scale={self.scale:.2f})"
    
    def to_svg(self) -> str:
        """Generate SVG <g> element with transformations."""
        # Convert center to pixel space (with y-flip)
        center_svg = np.conj(self.center)
        cx, cy = to_px(center_svg)
        
        # Build transformation string
        transforms = []
        
        # 1. Translate to position
        transforms.append(f"translate({np.round(cx, self.digits)} {np.round(cy, self.digits)})")
        
        # 2. Rotate (convert radians to degrees)
        if abs(self.rotation) > 1e-10:
            angle_deg = np.rad2deg(self.rotation)
            transforms.append(f"rotate({np.round(angle_deg, self.digits)})")
        
        # 3. Scale
        if abs(self.scale - 1.0) > 1e-10:
            transforms.append(f"scale({np.round(self.scale, self.digits)})")
        
        transform_str = " ".join(transforms)
        
        # Build group attributes
        base_attrs = {"transform": transform_str}
        attrs_str = build_svg_attrs(base_attrs, **self.svg_attrs)
        
        return f"<g {attrs_str}>\n{self.svg_content}\n</g>"
    
    def set_center(self, center: complex):
        """Change the center position."""
        self.center = center
        return self
    
    def set_scale(self, scale: float):
        """Change the scale factor."""
        self.scale = scale
        return self
    
    def set_rotation(self, rotation: float):
        """Change the rotation angle (radians)."""
        self.rotation = rotation
        return self
