import os
import numpy as np
from IPython.display import SVG, display
from abc import ABC, abstractmethod

class SVGElement(ABC):
    """
    Abstract base class for SVG elements with common styling.

    Parameters
    ----------
    fill : str, optional
        Fill color (default: "none")
    edgecolor : str, optional
        Edge color (default: "black")
    lw : float, optional
        Line width (default: 1.0)
    digits : int, optional
        Number of decimal digits for floating point numbers
        in the SVG string (default: 5)
    **svg_attrs : dict, optional
        Additional SVG attributes

    Notes
    -----
    SVG elements generated by this class will have the following common
    attributes: fill, stroke (edgecolor), and stroke-width (lw).
    """
    
    def __init__(
        self,
        fill: str = "none",
        edgecolor: str = "black",
        lw: float = 1.0,
        digits: int = 5,
        **svg_attrs,
    ):
        self.fill = fill
        self.edgecolor = edgecolor
        self.lw = lw
        self.digits = digits
        self.svg_attrs = svg_attrs
    
    @abstractmethod
    def to_svg(self) -> str:
        """Generate the SVG string representation."""
        pass
    
    def __repr__(self):
        """Developer-friendly representation."""
        attrs = ", ".join(f"{k}={v!r}" for k, v in self._get_repr_attrs().items())
        return f"{self.__class__.__name__}({attrs})"
    
    def __str__(self):
        """User-friendly representation."""
        return self._get_str_repr()
    
    def _get_repr_attrs(self) -> dict:
        """
        Override in subclasses to specify which attributes to show in repr.
        Default shows common styling attributes.
        """
        return {
            "fill": self.fill,
            "edgecolor": self.edgecolor,
            "lw": self.lw,
        }
    
    def _get_str_repr(self) -> str:
        """
        Override in subclasses for custom user-friendly string.
        Default returns class name.
        """
        return f"{self.__class__.__name__}"
    
    # Common setters
    def set_fill(self, color: str):
        """Change fill color."""
        self.fill = color
        return self
    
    def set_edgecolor(self, color: str):
        """Change edge color."""
        self.edgecolor = color
        return self
    
    def set_linewidth(self, lw: float):
        """Change line width."""
        self.lw = lw
        return self
    
    def set_attr(self, **attrs):
        """Set additional SVG attributes."""
        self.svg_attrs.update(attrs)
        return self
    
    def _build_base_attrs(self, extra: dict = None) -> dict:
        """Build common attributes dict."""
        attrs = {
            "fill": self.fill,
            "stroke": self.edgecolor,
            "stroke-width": self.lw,
        }
        if extra:
            attrs.update(extra)
        return attrs
    




class SVGCanvas:
    """
    Canvas holding SVG elements that can be modified before rendering.
    
    Parameters
    ----------
    center : tuple[float, float], optional
        Center coordinates (cx, cy) in disk space.
    radius : float, optional
        Disk radius in disk space.
    padding : float, optional
        Padding around the viewBox.
    width : int, optional
        SVG width in pixels.
    height : int, optional
        SVG height in pixels.
    """
    
    def __init__(
        self,
        center: tuple[float, float] = (0, 0),
        radius: float = 100.0,  # corresponds to scale factor in to_px (improve me!)
        padding: float = 5,
        width: int = 600,
        height: int = 600,
    ):
        self.elements: list[SVGElement] = []
        
        # SVG parameters
        self.center = center
        self.radius = radius
        self.padding = padding
        self.width = width
        self.height = height
    
    def add(self, *elements: SVGElement):
        """Add one or more elements."""
        self.elements.extend(elements)
        return self
    
    def remove(self, element: SVGElement):
        """Remove an element."""
        self.elements.remove(element)
        return self
    
    def clear(self):
        """Remove all elements."""
        self.elements.clear()
        return self
    
    def _build_header(self) -> str:
        """Build SVG opening tag with viewBox."""
        cx, cy = self.center
        r = self.radius
        vb_min_x = cx - r - self.padding
        vb_min_y = cy - r - self.padding
        vb_width = 2 * r + 2 * self.padding
        vb_height = 2 * r + 2 * self.padding
        
        return (
            f"<svg xmlns='http://www.w3.org/2000/svg' "
            f"width='{self.width}' height='{self.height}' "
            f"viewBox='{vb_min_x} {vb_min_y} {vb_width} {vb_height}'>\r"
        )
    
    def _build_footer(self) -> str:
        """Build SVG closing tag."""
        return "</svg>\r"
    
    def render(self) -> str:
        """Render complete SVG document."""
        parts = [self._build_header()]
        
        # Add all elements in order
        for elem in self.elements:
            parts.append(elem.to_svg())
            parts.append("\r")
        
        parts.append(self._build_footer())
        return "".join(parts)
    
    def save(self, filename: str):
        """Save SVG to file."""
        with open(filename, 'w') as f:
            f.write(self.render())
        return self
    
    # Collection interface
    def __len__(self): 
        return len(self.elements)
    
    def __getitem__(self, idx): 
        return self.elements[idx]
    
    def __iter__(self): 
        return iter(self.elements)
    
    def __repr__(self):
        return f"SVGCanvas({len(self.elements)} elements)"

def build_svg_attrs(base_attrs: dict, **svg_attrs) -> str:
    """
    Merge base attributes with additional SVG attributes.
    Converts underscores to hyphens (stroke_width -> stroke-width).
    svg_attrs override base_attrs.
    
    Example:
        build_svg_attrs({"fill": "red", "stroke": "black"}, opacity=0.5)
        # Returns: "fill='red' stroke='black' opacity='0.5'"
    """
    base_attrs.update({k.replace('_', '-'): v for k, v in svg_attrs.items()})
    return " ".join(f"{k}='{v}'" for k, v in base_attrs.items())


def to_px(z, factor=100):
    """
    Transforms complex number to px coordinates

    Arguments:
    ----------
    z : np.complex
        coordinate in the complex plane
    factor : int
        some large scaling factor to conform to px scale
    """
    x = np.real(z)
    x *= factor
    y = np.imag(z)
    y *= factor
    return x, y



def draw_svg(content: str):
    """
    Use IPython display API for displaying SVG
    """
    display(SVG(data=content))


def write_svg(fname: str, content: str):
    """
    Write svgString to file
    
    Parameters
    ----------
    fname : str
        filename to write the svg string to
    content : str
        svg string to write to file
    """
    os.remove(fname) if os.path.exists(fname) else None
    svgfile = open(fname, 'w')
    svgfile.write(content)
    svgfile.close()

